language: node_js
node_js: '8'
cache:
  directories:
    - node_modules
install:
  - npm install -g
  - npm install
before_script:
  - npm run lint
  - npm run eslint
script: npm run build
deploy:
  local-dir: build/es6-bundled
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  'on':
    branch: master

